---
title: "almond yield function"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
#read in libraries

library(tidyverse)
library(here)
library(janitor)
```

```{r}
# read in data

data <- read_table(here("clim.txt")) |> 
  clean_names()
```


```{r}

almond_yield <- function(data){

data_filter <- data |> 
  filter(month == 2 | month == 1) |> 
  group_by(month, year) |> 
  summarize(mean_min_temp = mean(tmin_c),
            total_precip = sum(precip)) |> 
  ungroup() |> 
  pivot_wider(
    names_from = month,
    values_from = c(mean_min_temp, total_precip)
  ) |> 
  select(-mean_min_temp_1, - total_precip_2) |> 
  mutate(yield = (-0.015 * mean_min_temp_2 - 0.0046 * mean_min_temp_2^2 - 0.07 * total_precip_1 + 0.0043 * total_precip_1^2 + 0.28)) 
  yield_results <- c(min_yield = min(data_filter$yield), 
                     mean_yield = mean((data_filter$yield)),
                     max_yield = max((data_filter$yield)))

  return(yield_results)
}

almond_yield(data)

```
